version: "3"
services:
  select_stock_code:
    image: check_reward
    container_name: "check_reward"
    environment:
      CHECK_REWARD_RESULT_DIR: check_reward_result_dir
      LOG_DIR: log_dir
      SELECT_CODE_DIR: select_code_dir
    volumes:
      - ${CHECK_REWARD_RESULT_DIR}:/select_stock_code/check_reward/result/reward
      - ${LOG_DIR}:/select_stock_code/helper/log
      - ${SELECT_CODE_DIR}:/select_stock_code/check_reward/result/selected_code
    command: sh /select_stock_code/check_reward/check_reward.sh
