version: "3.7"
services:
  select_stock_code:
    image: ${IMAGE_NAME}
    container_name: "select_stock_code"
    environment:
      DOWNLOAD_DIR: download_dir
      LOG_DIR: log_dir
      SELECT_CODE_DIR: select_code_dir
    volumes:
      - ${SCRIPT_DIR}:/select_stock_code
      - ${DOWNLOAD_DIR}:/select_stock_code/get_stock_info/stock_data
      - ${LOG_DIR}:/select_stock_code/helper/log
      - ${SELECT_CODE_DIR}:/select_stock_code/check_reward/result/selected_code
      - ${GRAPH_DIR}:/select_stock_code/draw_graph/graphs
      - ${TEST_DIR}:/select_stock_code/test
    ports:
      - "8888:8888"
    deploy:
      resources:
        limits:
          memory: 1.2G
    #command: sh ./stock_strategy/strategies_back_test.sh
