FROM python:3.6-slim

COPY ./requirements_lib /usr/local/lib/python3.6/site-packages

WORKDIR /usr/local/lib/python3.6/site-packages
RUN ls
RUN tar -zxvf jsm.gz
WORKDIR /usr/local/lib/python3.6/site-packages/jsm-0.19-py3.6.egg-info
RUN pip install -r requires.txt

RUN pip install \
  joblib\
  numpy\
  pandas\
  Quandl\
  lxml\
  xlrd\
  requests\
  matplotlib\
  mpl_finance\
  logzero

WORKDIR /
