FROM python:3.6-slim

# for jsm
COPY ./requirements_lib /usr/local/lib/python3.6/site-packages

WORKDIR /usr/local/lib/python3.6/site-packages
RUN ls
RUN tar -zxvf jsm.gz
WORKDIR /usr/local/lib/python3.6/site-packages/jsm-0.19-py3.6.egg-info
RUN pip install -r requires.txt

WORKDIR /home/setup
COPY ./requirements.txt .
RUN apt-get update
RUN apt-get install -y build-essential libssl-dev libffi-dev python3-dev
RUN pip install -U pip
RUN pip install cython
RUN pip install -r requirements.txt
